//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageGun.DomainModel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MqMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MqMessages()
        {
            this.TeleMessages = new HashSet<TeleMessages>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Phone { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeleMessages> TeleMessages { get; set; }
    }
}
