//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageGun.DomainModel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleMessages
    {
        public int Id { get; set; }
        public int id_messages { get; set; }
        public bool Sended { get; set; }
        public string Description { get; set; }
    
        public virtual MqMessages MqMessages { get; set; }
    }
}
